### ISSUE TITLE
Bashism in debian.sh (Debian doesn't use bash as default /bin/sh)

### ISSUE THREAD

**Issue by jmaslibre** [hashicorp/puppet-bootstrap#37]
Within Debian, the default /bin/sh is Dash[0] [1].
(Since Debian Squeeze)

There is a "bash-ism" in puppet-bootstrap/debian.sh line 22   [2],
$EUID should be "$(id -u)", or you could change the shebang to use explicitly "bash" instead of sh.

Using the current script you get the message:
"==> default: /tmp/vagrant-shell: 22: [: Illegal number:"
that is cause by this issue.

[0] https://wiki.debian.org/Shell
[1] https://packages.debian.org/dash
[2] https://github.com/hashicorp/puppet-bootstrap/blob/master/debian.sh#L22

**Comment by grubernaut** [comment]
Fixed in #42

**Comment by jmaslibre** [comment]
Hi @grubernaut,

I think the bug is still present, the script still uses EUID and
Debian uses Dash as /bin/sh, and Dash only supports POSIX
features. $EUID is not part of POSIX, and is not available in Dash.

**Comment by jmaslibre** [comment]
FWIW I added the pull request #49 with my proposal to fix this,

Kind Regards, and thanks for sharing your work.
